# Site settings
title: Calsy
subtitle: Financial Planning Calculators
email: 
description: 
baseurl: "/calsy" # the subpath of your site, e.g. /blog
url: "https://calsy.tk/" # the base hostname & protocol for your site
